 
CREATE TABLE DEPARTAMENTO(
  COD_DEPART NUMBER,
  NOME VARCHAR2(100) NOT NULL,
  DATA_INICIAL DATE,
  CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (COD_DEPART)
)
//

CREATE TABLE LOCALIZACAO(
  COD_LOC NUMBER,
  COD_DEPART NUMBER,
  LOC_LOCAL VARCHAR2(252),
  CONSTRAINT PK_LOCALIZACAO PRIMARY KEY (COD_LOC),
  CONSTRAINT FK_LOCALIZACAO_COD_DEPART
    FOREIGN KEY (COD_DEPART) REFERENCES DEPARTAMENTO(COD_DEPART)
)
//

CREATE TABLE FUNCIONARIO(
  COD_FUNC NUMBER,
  FUNC_NOME VARCHAR2(100) NOT NULL,
  FUNC_CPF VARCHAR2(15),
  FUNC_SALARIO DECIMAL(4,2),
  FUNC_ENDERECO VARCHAR2(252),
  FUNC_SEXO CHAR,
  COD_SUPER NUMBER,
  COD_DEPART NUMBER,
  CONSTRAINT UK_FUNCIONARIO_FUNC_CPF UNIQUE (FUNC_CPF),
  CONSTRAINT CK_FUNCIONARIO_FUNC_SEXO CHECK (FUNC_SEXO IN ('M', 'F')),
  CONSTRAINT CK_FUNCIONARIO_FUNC_SALARIO CHECK (FUNC_SALARIO > 1000),
  CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (COD_FUNC),
  CONSTRAINT FK_FUNCIONARIO_COD_DEPART
    FOREIGN KEY (COD_DEPART) REFERENCES DEPARTAMENTO(COD_DEPART),
  CONSTRAINT FK_FUNCIONARIO_COD_SUPER
    FOREIGN KEY (COD_SUPER) REFERENCES FUNCIONARIO(COD_FUNC)
)
//

CREATE TABLE DEPENDENTE(
  COD_DEP NUMBER,
  COD_FUNC NUMBER,
  DEP_SEQ NUMBER,
  DEP_NOME VARCHAR2(100) NOT NULL,
  DEP_PARENTESCO VARCHAR2(30) NOT NULL,
  DEP_DATA_NASC DATE,
  CONSTRAINT CK_FUNCIONARIO_DEP_PARENTESCO
    CHECK (DEP_PARENTESCO IN ('PAI','MAE', 'IRMAO', 'FILHO')),
  CONSTRAINT PK_DEPENDENTE PRIMARY KEY (COD_DEP),
  CONSTRAINT FK_FUNCIONARIO_COD_FUNC
    FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC)
)
//

CREATE TABLE PROJETO(
  COD_PROJ NUMBER,
  COD_DEPART NUMBER,
  PROJ_TITULO VARCHAR2(150) NOT NULL,
  PROJ_DESCRICAO VARCHAR2(252),
  PROJ_DATA_CAD DATE DEFAULT SYSDATE,
  CONSTRAINT PK_PROJETO PRIMARY KEY (COD_PROJ),
  CONSTRAINT FK_PROJETO_COD_DEPART
    FOREIGN KEY (COD_DEPART) REFERENCES DEPARTAMENTO(COD_DEPART)
)
//

CREATE TABLE PARTICIPA(
  COD_FUNC NUMBER,
  COD_PROJ NUMBER,
  PART_HORAS VARCHAR2(50),
  CONSTRAINT PK_PARTICIPA PRIMARY KEY (COD_FUNC,COD_PROJ),
  CONSTRAINT FK_PARTICIPA_COD_FUNC
    FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC),
  CONSTRAINT FK_PARTICIPA_COD_PROJ
    FOREIGN KEY (COD_PROJ) REFERENCES PROJETO(COD_PROJ)
)
//
