CREATE TABLE DEPARTAMENTO(
  COD_DEPART NUMBER(4),
  NOME VARCHAR2(100) NOT NULL,
  DATA_INICIAL DATE,
  CONSTRAINT PK_DEPARTAMENTO PRIMARY KEY (COD_DEPART)
)
//

CREATE TABLE LOCALIZACAO(
  COD_DEPART NUMBER(4),
  LOC_LOCAL VARCHAR2(252),
  CONSTRAINT PK_LOCALIZACAO PRIMARY KEY (COD_DEPART, LOC_LOCAL),
  CONSTRAINT FK_LOCALIZACAO_COD_DEPART
    FOREIGN KEY (COD_DEPART) REFERENCES DEPARTAMENTO(COD_DEPART)
)
//

CREATE TABLE FUNCIONARIO(
  COD_FUNC NUMBER(4),
  FUNC_NOME VARCHAR2(100) NOT NULL,
  FUNC_CPF VARCHAR2(15),
  FUNC_SALARIO DECIMAL(4,2),
  FUNC_ENDERECO VARCHAR2(252),
  FUNC_SEXO CHAR(1),
  COD_SUPER NUMBER(4),
  COD_DEPART NUMBER(4),
  CONSTRAINT UK_FUNCIONARIO_FUNC_CPF UNIQUE (FUNC_CPF),
  CONSTRAINT CK_FUNCIONARIO_FUNC_SEXO CHECK (FUNC_SEXO IN ('M', 'F')),
  CONSTRAINT CK_FUNCIONARIO_FUNC_SALARIO CHECK (FUNC_SALARIO > 1000),
  CONSTRAINT PK_FUNCIONARIO PRIMARY KEY (COD_FUNC),
  CONSTRAINT FK_FUNCIONARIO_COD_DEPART
    FOREIGN KEY (COD_DEPART) REFERENCES DEPARTAMENTO(COD_DEPART),
  CONSTRAINT FK_FUNCIONARIO_COD_SUPER
    FOREIGN KEY (COD_SUPER) REFERENCES FUNCIONARIO(COD_FUNC)
)
//

CREATE TABLE DEPENDENTE(
  COD_DEP NUMBER(4),
  COD_FUNC NUMBER(4),
  DEP_SEQ NUMBER(4),
  DEP_NOME VARCHAR2(100) NOT NULL,
  DEP_PARENTESCO VARCHAR2(30) NOT NULL,
  DEP_DATA_NASC DATE,
  CONSTRAINT CK_FUNCIONARIO_DEP_PARENTESCO
    CHECK (DEP_PARENTESCO IN ('PAI','MAE', 'IRMAO', 'FILHO')),
  CONSTRAINT PK_DEPENDENTE PRIMARY KEY (COD_DEP),
  CONSTRAINT FK_FUNCIONARIO_COD_FUNC
    FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC)
)
//

CREATE TABLE PROJETO(
  COD_PROJ NUMBER(4),
  COD_DEPART NUMBER(4),
  PROJ_TITULO VARCHAR2(150) NOT NULL,
  PROJ_DESCRICAO VARCHAR2(252),
  PROJ_DATA_CAD DATE DEFAULT SYSDATE,
  CONSTRAINT PK_PROJETO PRIMARY KEY (COD_PROJ),
  CONSTRAINT FK_PROJETO_COD_DEPART
    FOREIGN KEY (COD_DEPART) REFERENCES DEPARTAMENTO(COD_DEPART)
)
//

CREATE TABLE PARTICIPA(
  COD_FUNC NUMBER(4),
  COD_PROJ NUMBER(4),
  PART_HORAS VARCHAR2(50),
  CONSTRAINT PK_PARTICIPA PRIMARY KEY (COD_FUNC,COD_PROJ),
  CONSTRAINT FK_PARTICIPA_COD_FUNC
    FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC),
  CONSTRAINT FK_PARTICIPA_COD_PROJ
    FOREIGN KEY (COD_PROJ) REFERENCES PROJETO(COD_PROJ)
)
//

ALTER TABLE PROJETO ADD PROJ_STATUS NUMBER(1) CHECK (PROJ_STATUS IN (0, 1)) NOT NULL//
ALTER TABLE PROJETO MODIFY PROJ_TITULO VARCHAR2(252)//
ALTER TABLE PROJETO RENAME COLUMN PROJ_DATA_CAD TO PROJ_DATA_CADASTRO//

CREATE TABLE ENDERECO(
  COD_END NUMBER(4),
  END_ENDERECO VARCHAR2(150) NOT NULL,
  CONSTRAINT PK_ENDERECO PRIMARY KEY (COD_END)
)
//

CREATE TABLE FUNCIONARIO_ENDERECO(
  COD_END NUMBER(4),
  COD_FUNC NUMBER(4),
  CONSTRAINT PK_FUNCIONARIO_ENDERECO PRIMARY KEY (COD_END, COD_FUNC),
  CONSTRAINT FK_FUNC_END_COD_FUNC
    FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC),
  CONSTRAINT FK_FUNC_END_COD_END
    FOREIGN KEY (COD_END) REFERENCES ENDERECO(COD_END)
)
//

ALTER TABLE FUNCIONARIO DROP COLUMN FUNC_ENDERECO//
ALTER TABLE FUNCIONARIO DROP CONSTRAINT CK_FUNCIONARIO_FUNC_SALARIO//

ALTER TABLE FUNCIONARIO DISABLE CONSTRAINT UK_FUNCIONARIO_FUNC_CPF//
ALTER TABLE FUNCIONARIO ENABLE CONSTRAINT UK_FUNCIONARIO_FUNC_CPF//

CREATE TABLE PARENTESCO(
  COD_PAR NUMBER(4),
  PAR_DESCRICAO VARCHAR2(50),
  CONSTRAINT PK_PARENTESCO PRIMARY KEY (COD_PAR)
)
//

ALTER TABLE DEPENDENTE ADD COD_PAR NUMBER//
ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_COD_PAR
    FOREIGN KEY (COD_PAR) REFERENCES PARENTESCO(COD_PAR)//

ALTER TABLE DEPENDENTE DROP COLUMN DEP_PARENTESCO//

ALTER TABLE DEPENDENTE ADD DEP_CPF VARCHAR2(15)//
ALTER TABLE DEPENDENTE ADD CONSTRAINT
  UK_DEPENDENTE_DEP_CPF UNIQUE (DEP_CPF)//

ALTER TABLE DEPENDENTE DROP CONSTRAINT FK_FUNCIONARIO_COD_FUNC//
ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_FUNCIONARIO_COD_FUNC
  FOREIGN KEY (COD_FUNC) REFERENCES FUNCIONARIO(COD_FUNC)
  ON DELETE CASCADE//

RENAME PARTICIPA TO FUNC_PROJETO//